set_property PACKAGE_PIN F13 [get_ports tx]

set_property PACKAGE_PIN AK15 [get_ports CLK_74_25_P]
set_property PACKAGE_PIN AK14 [get_ports CLK_74_25_N]
set_property IOSTANDARD LVDS_25 [get_ports CLK_74_25_P]
set_property IOSTANDARD LVDS_25 [get_ports CLK_74_25_N]

set_property PACKAGE_PIN AD7 [get_ports {ad_os[0]}]
set_property PACKAGE_PIN AD2 [get_ports {ad_os[1]}]
set_property PACKAGE_PIN AE8 [get_ports {ad_os[2]}]
set_property PACKAGE_PIN AH3 [get_ports ad_convstab]
set_property PACKAGE_PIN AH2 [get_ports ad_reset]
set_property PACKAGE_PIN AE5 [get_ports ad_rd]
set_property PACKAGE_PIN AF2 [get_ports ad_cs]
set_property PACKAGE_PIN AD4 [get_ports ad_busy]
set_property PACKAGE_PIN AE3 [get_ports first_data]

set_property PACKAGE_PIN AJ6 [get_ports {ad_data[0]}]
set_property PACKAGE_PIN AJ5 [get_ports {ad_data[1]}]
set_property PACKAGE_PIN AD1 [get_ports {ad_data[2]}]
set_property PACKAGE_PIN AJ1 [get_ports {ad_data[3]}]
set_property PACKAGE_PIN AF1 [get_ports {ad_data[4]}]
set_property PACKAGE_PIN AE4 [get_ports {ad_data[5]}]
set_property PACKAGE_PIN AF3 [get_ports {ad_data[6]}]
set_property PACKAGE_PIN AF5 [get_ports {ad_data[7]}]
set_property PACKAGE_PIN AJ2 [get_ports {ad_data[8]}]
set_property PACKAGE_PIN AG3 [get_ports {ad_data[9]}]
set_property PACKAGE_PIN AE2 [get_ports {ad_data[10]}]
set_property PACKAGE_PIN AH1 [get_ports {ad_data[11]}]
set_property PACKAGE_PIN AF8 [get_ports {ad_data[12]}]
set_property PACKAGE_PIN AD6 [get_ports {ad_data[13]}]
set_property PACKAGE_PIN AG8 [get_ports {ad_data[14]}]
set_property PACKAGE_PIN AH8 [get_ports {ad_data[15]}]


set_property IOSTANDARD LVCMOS18 [get_ports tx]
set_property IOSTANDARD LVCMOS18 [get_ports ad_convstab]
set_property IOSTANDARD LVCMOS18 [get_ports ad_reset]
set_property IOSTANDARD LVCMOS18 [get_ports ad_rd]
set_property IOSTANDARD LVCMOS18 [get_ports ad_cs]
set_property IOSTANDARD LVCMOS18 [get_ports ad_busy]
set_property IOSTANDARD LVCMOS18 [get_ports first_data]
set_property IOSTANDARD LVCMOS18 [get_ports {ad_os[*]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ad_data[*]}]